### ISSUE TITLE
AppsFlyerLib not loaded

### ISSUE THREAD

**Issue by doganaltinbas** [AppsFlyerSDK/appsflyer-framework-ars-beta#1]
Hello, 
Currently, I have installed both `AppsFlyerLib`(6.6.1) and `PurchaseConnector`. However, when I run app, I got following error:
`Library not loaded: @rpath/AppsFlyerLib.framework/AppsFlyerLib`

Any help would be appreciated.

**Comment by af-obodovskyi** [comment]
@doganaltinbas, @andr-ggn, @af-fess closing, the issue, was fixed in merge pull request #2
